source 'https://rubygems.org'
gem 'rails', '3.2.13'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem "mongoid", "2.0.2"
gem "devise", ">= 2.2.3"
gem "quiet_assets", ">= 1.0.2", :group => :development
gem "mongoid-sequence"
gem "bson_ext"

